---

- name: apache.yml | Install Apache
  hosts: "{{ target }}"
  become: yes

  tasks:

  - name: Install Apache Package Dependencies
    apt: pkg={{ item }} state=present
    with_items:
      - apache2

  - name: Create Cleanwall Apache Directory
    file:
      path: /usr/local/cleanwall/apache
      recurse: yes
      state: directory
      mode: 0755
      owner: administrator
      group: administrator

  - name: Install Cleanwall Apache Configs
    become: no
    synchronize:
      src: files/usr/local/cleanwall/apache/
      dest: /usr/local/cleanwall/apache

  - name: Enable Apache SSL Module
    apache2_module:
      state: present
      name: ssl

  - name: Enable Apache include Module
    apache2_module:
      state: present
      name: include

  - name: Enable Apache cgid Module
    apache2_module:
      state: present
      name: cgid

  - name: Enable Apache rewrite Module
    apache2_module:
      state: present
      name: rewrite

  - name: Enable Apache headers Module
    apache2_module:
      state: present
      name: headers

  - name: Create Web Content Directory
    file:
      path: /var/www
      state: directory
      mode: 0755
      owner: administrator
      group: administrator

  - name: Install Web Content
    become: no
    synchronize:
      src: files/var/www/
      dest: /var/www

  - name: Copy /etc/apache2/ports.conf
    copy: src=etc/apache2/ports.conf dest=/etc/apache2/

  - name: Copy /etc/apache2/sites-available/000-default.conf
    copy: src=etc/apache2/sites-available/000-default.conf dest=/etc/apache2/sites-available/

  - name: Copy /etc/apache2/sites-available/013-sorry-police-ssl.conf
    copy: src=etc/apache2/sites-available/013-sorry-police-ssl.conf dest=/etc/apache2/sites-available/

  - name: Copy /etc/apache2/sites-available/020-web2py-ssl.conf
    copy: src=etc/apache2/sites-available/020-web2py-ssl.conf dest=/etc/apache2/sites-available/

  - name: Copy /etc/apache2/sites-available/www.lan-ssl.conf
    copy: src=etc/apache2/sites-available/www.lan-ssl.conf dest=/etc/apache2/sites-available/

#  - name: Copy /etc/apache2/sites-available/default-ssl.conf
#    copy: src=etc/apache2/sites-available/default-ssl.conf dest=/etc/apache2/sites-available/

  - name: Disable Default SSL Site
    command: a2ensite www.lan-ssl.conf

  - name: Enable Site https://www.lan
    command: a2ensite www.lan-ssl.conf

# get full latest /var/www 
