---

- name: hardware.yml | Install Hardware Specific Parts
  hosts: "{{ target }}"
  become: yes

  tasks:

  - name: Install Hardware Specific Packages
    yum: pkg={{ item }} state=present
    with_items:
      - lm-sensors

  - name: Add the temperature sensor kernel module
    modprobe:
      name: coretemp
      state: present

