---

- name: install-redwood.yml | Install Redwood and Dependencies
  hosts: "{{ target }}"
  become: no

  tasks:

  - name: Install Redwood Build Package Dependencies
    become: yes
    apt: pkg={{ item }} state=present
    with_items:
      - git-core
      - golang-1.8-src
      - golang-1.8-go
      - golang-1.8-doc
      - golang-1.8

  - name: Set GOPATH for all users
    become: yes
    copy:
      src: etc/profile.d/go-path.sh
      dest: /etc/profile.d

  - name: Create go build Directory
    become: yes
    file:
      path: /usr/local/cleanwall/go
      state: directory
      mode: 0755
      owner: administrator
      group: administrator

  - name: Get Redwood Cascadia Dependency from Github
    git:
      repo: https://github.com/andybalholm/cascadia.git
      dest: /usr/local/cleanwall/go/src/github.com/andybalholm/cascadia

  - name: Get Redwood dhash Dependency from Github
    git:
      repo: https://github.com/andybalholm/dhash.git
      dest: /usr/local/cleanwall/go/src/github.com/andybalholm/dhash

  - name: Get Redwood go-bit Dependency from Github
    git:
      repo: https://github.com/andybalholm/go-bit.git
      dest: /usr/local/cleanwall/go/src/github.com/andybalholm/go-bit

  - name: Get Redwood gzip Dependency from Github
    git:
      repo: https://github.com/klauspost/compress.git
      dest: /usr/local/cleanwall/go/src/github.com/klauspost/compress

  - name: Get Redwood cpuid Dependency from Github
    git:
      repo: https://github.com/klauspost/cpuid.git
      dest: /usr/local/cleanwall/go/src/github.com/klauspost/cpuid

  - name: Get Redwood go-gypsy Dependency from Github
    git:
      repo: https://github.com/kylelemons/go-gypsy.git
      dest: /usr/local/cleanwall/go/src/github.com/kylelemons/go-gypsy

  - name: Get Redwood dns Dependency from Github
    git:
      repo: https://github.com/miekg/dns.git
      dest: /usr/local/cleanwall/go/src/github.com/miekg/dns

  - name: Get Redwood ftpget Dependency from Github
    git:
      repo: https://github.com/remogatto/ftpget.git
      dest: /usr/local/cleanwall/go/src/github.com/remogatto/ftpget

  - name: Get Redwood golang html Dependency
    command: go get golang.org/x/net/html
    args:
      chdir: /usr/local/cleanwall/go/src
      creates: /usr/local/cleanwall/go/src/golang.org/x/net/html
    environment:
      GOPATH: /usr/local/cleanwall/go

  - name: Get Redwood golang text Dependency
    command: go get golang.org/x/text
    args:
      chdir: /usr/local/cleanwall/go/src
      creates: /usr/local/cleanwall/go/src/golang.org/x/text
    environment:
      GOPATH: /usr/local/cleanwall/go


  - name: Get Redwood Main Executable Source from Github
    git:
      repo: https://github.com/andybalholm/redwood.git
      dest: /usr/local/cleanwall/go/src/github.com/andybalholm/redwood
#      force: yes
      update: no

  - name: Get Redwood Shadow Bot Config from Github
    git:
      repo: https://github.com/renatomercurio/redwood-config.git
      dest: /usr/local/cleanwall/go/src/github.com/renatomercurio/redwood-config
#      force: yes
      update: no

  - name: Create Symbolic Link for Redwood Config 
    become: yes
    file:
      src: "/usr/local/cleanwall/go/src/github.com/renatomercurio/redwood-config"
      dest: "/etc/redwood"
      state: link

  - name: Set User Agent Patch for Testmode
    lineinfile:
      dest: /usr/local/cleanwall/go/src/github.com/andybalholm/redwood/testmode.go
      regexp: 'User-Agent'
      insertbefore: 'reqACLs :'
      line: '	req.Header.Set("User-Agent", "Mozilla")'

  - name: Build the Redwood Golang Binary
    command: /usr/lib/go-1.8/bin/go install github.com/andybalholm/redwood
    args:
      chdir: /usr/local/cleanwall/go/src
      creates: /usr/local/cleanwall/go/bin/redwood
    environment:
      GOPATH: /usr/local/cleanwall/go


#cp redwood /usr/local/cleanwall/redwood/bin/


# use apache/certs certificates
#
# ### Redwood Init Script
# ```
# mkdir /var/log/redwood
# vim /lib/systemd/system/redwood.service
# cd /etc/systemd/system/multi-user.target.wants/
# ln -s /lib/systemd/system/redwood.service redwood.service
# systemctl daemon-reload
# systemctl enable redwood.service
# systemctl start redwood.service
# ```


#cd /usr/local/c1/redwood/
#go get github.com/cm/redwood-config
#  - name: Install Redwood Config for Bot Use
#    synchronize: src=.../github.com/cw/redwood-config dest=/usr/local/c1/redwood/
#

