---

- name: router.yml | Install Router Network with Wireless AP
  hosts: "{{ target }}"
  become: yes

  tasks:

  - name: Copy /etc/sysctl.conf
    copy: src=etc/sysctl.conf dest=/etc/sysctl.conf

  - name: Disable systemd Device Renaming
    lineinfile:
      dest: /etc/default/grub
      regexp: '^GRUB_CMDLINE_LINUX='
      line: 'GRUB_CMDLINE_LINUX="net.ifnames=0 biosdevname=0"'

  - name: update grub
    command: update-grub

  - name: Copy /etc/network/interfaces
    copy: src=etc/network/interfaces dest=/etc/network/

  - name: Copy /etc/hosts
    copy: src=etc/hosts dest=/etc/

  - name: Copy /etc/resolv.conf
    copy: src=etc/resolv.conf dest=/etc/

  - name: Install Wireless Package Dependencies
    apt: pkg={{ item }} state=present
    with_items:
      - iw
      - wireless-tools
      - wpasupplicant
      - hostapd

  - name: Copy /etc/default/hostapd
    copy: src=etc/default/hostapd dest=/etc/default/

  - name: Copy /usr/local/cleanwall/wlan/hostapd.conf
    copy: src=usr/local/cleanwall/wlan/hostapd.conf dest=/usr/local/cleanwall/wlan/

  - name: Install DHCP Server Package
    apt: pkg={{ item }} state=present
    with_items:
      - isc-dhcp-server

  - name: Copy /etc/dhcp/dhcpd.conf
    copy: src=etc/dhcp/dhcpd.conf dest=/etc/dhcp/

  - name: Copy /etc/dhcp/dhclient.conf
    copy: src=etc/dhcp/dhclient.conf dest=/etc/dhcp/

  - name: Copy /etc/default/isc-dhcp-server
    copy: src=etc/default/isc-dhcp-server dest=/etc/default/

  - name: Install exim4 Email
    apt: pkg={{ item }} state=present
    with_items:
      - exim4


