---

- name: server.yml | Install Basic Server
  hosts: "{{ target }}"
  become: yes

  tasks:

  - name: Install Basic Server Package Dependencies
    apt: pkg={{ item }} state=present
    with_items:
      - ssh
      - openssh-server
      - vim
      - locales-all
      - aptitude
      - lshw
      - strace
      - curl
      - tcpdump
      - rsync

  - name: Debian System Upgrade
    apt:
      update_cache=yes upgrade=yes
    register: results_debian

