---

- name: example.yml | Simple Basic Config Example
  hosts: "{{ target }}"
  become: yes

  tasks:

  - name: Configure SSSD template copy and notify example
    template: src=files/sys/sssd.conf.j2 dest=/etc/sssd/sssd.conf
              owner=root group=root mode=0600
    notify: restart sssd

  - name: Ensure timesyncd is started and enabled on boot
    service: name=systemd-timesyncd state=started enabled=yes


  handlers:

  - name: restart sssd
    service: name=sssd state=restarted


