CREATE TABLE Domain(Id INTEGER PRIMARY KEY, Name TEXT, Level INTEGER, sourceid INTEGER, CategoryName TEXT, CatId INTEGER, Cat2Id INTEGER, Cat3Id INTEGER, Invariance INTEGER, Pcountry TEXT);
CREATE TABLE Category(Id INTEGER PRIMARY KEY, Name TEXT, Desc TEXT);
CREATE TABLE Source(Id INTEGER PRIMARY KEY, Name TEXT, Desc TEXT);
CREATE INDEX DomNameIdx ON Domain (Name);
